# Generated by Django 2.0.3 on 2018-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0002_remove_todo_isdone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_text',
            new_name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.BooleanField(default=True),
        ),
    ]
