# Generated by Django 2.0.3 on 2018-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0003_auto_20180318_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
            ],
        ),
    ]
