# Generated by Django 2.0.3 on 2018-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
